spring:
  application:
    name: myshop-api

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/myshopdb
    username: myshopdbuser
    password: myshopdbuser

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  logging:
    level:
      org.springframework.security.web: trace

  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-minutes: ${ACCESS_EXPIRED}
    refresh-token-expiration-minutes: ${REFRESH_EXPIRED}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0